In [13]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [18]:
from google.colab import files
uploaded = files.upload()

Saving hr dataset.csv to hr dataset.csv

In [25]:
import pandas as pd
df = pd.read_csv('hr dataset.csv')

In [20]:

df.head()

,Age,Attrition,Business_Travel,Daily_Rate,Department,Distance_From_Home,Education,Education_Field,Employee_Count,Employee_Number,Environment_Satisfaction,Gender,Hourly_Rate,Job_Involvement,Job_Level,Job_Role,Job_Satisfaction,Marital_Status,Monthly_Income,Monthly_Rate,NumCompanies_Worked,Over18,Over_Time,Percent_Salary_Hike,Performance_Rating,Relationship_Satisfaction,Standard_Hours,Stock_Option_Level,Total_Working_Years,Training_Times_LastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,age_group,Experience_Group,Attrition_flag,Month
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5,36-45,5+,1,Jan-1900
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7,45+,5+,0,Jan-1900
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0,36-45,0-2,1,Jan-1900
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0,25-35,5+,0,Jan-1900
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2,25-35,3-5,0,Jan-1900

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 39 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1470 non-null   int64
 1   Attrition                  1470 non-null   object
 2   Business_Travel            1470 non-null   object
 3   Daily_Rate                 1470 non-null   int64
 4   Department                 1470 non-null   object
 5   Distance_From_Home         1470 non-null   int64
 6   Education                  1470 non-null   int64
 7   Education_Field            1470 non-null   object
 8   Employee_Count             1470 non-null   int64
 9   Employee_Number            1470 non-null   int64
 10  Environment_Satisfaction   1470 non-null   int64
 11  Gender                     1470 non-null   object
 12  Hourly_Rate                1470 non-null   int64
 13  Job_Involvement            1470 non-null   int64
 14  Job_Level                  1470 non-null   int64
 15  Job_Role                   1470 non-null   object
 16  Job_Satisfaction           1470 non-null   int64
 17  Marital_Status             1470 non-null   object
 18  Monthly_Income             1470 non-null   int64
 19  Monthly_Rate               1470 non-null   int64
 20  NumCompanies_Worked        1470 non-null   int64
 21  Over18                     1470 non-null   object
 22  Over_Time                  1470 non-null   object
 23  Percent_Salary_Hike        1470 non-null   int64
 24  Performance_Rating         1470 non-null   int64
 25  Relationship_Satisfaction  1470 non-null   int64
 26  Standard_Hours             1470 non-null   int64
 27  Stock_Option_Level         1470 non-null   int64
 28  Total_Working_Years        1470 non-null   int64
 29  Training_Times_LastYear    1470 non-null   int64
 30  WorkLifeBalance            1470 non-null   int64
 31  YearsAtCompany             1470 non-null   int64
 32  YearsInCurrentRole         1470 non-null   int64
 33  YearsSinceLastPromotion    1470 non-null   int64
 34  YearsWithCurrManager       1470 non-null   int64
 35  age_group                  1470 non-null   object
 36  Experience_Group           1470 non-null   object
 37  Attrition_flag             1470 non-null   int64
 38  Month                      1470 non-null   object
dtypes: int64(27), object(12)
memory usage: 448.0+ KB

In [8]:
df.shape

(1470, 39)

In [10]:
df.isnull().sum()

Age                          0
Attrition                    0
Business_Travel              0
Daily_Rate                   0
Department                   0
Distance_From_Home           0
Education                    0
Education_Field              0
Employee_Count               0
Employee_Number              0
Environment_Satisfaction     0
Gender                       0
Hourly_Rate                  0
Job_Involvement              0
Job_Level                    0
Job_Role                     0
Job_Satisfaction             0
Marital_Status               0
Monthly_Income               0
Monthly_Rate                 0
NumCompanies_Worked          0
Over18                       0
Over_Time                    0
Percent_Salary_Hike          0
Performance_Rating           0
Relationship_Satisfaction    0
Standard_Hours               0
Stock_Option_Level           0
Total_Working_Years          0
Training_Times_LastYear      0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager         0
age_group                    0
Experience_Group             0
Attrition_flag               0
Month                        0
dtype: int64

In [26]:
df.head()

,Age,Attrition,Business_Travel,Daily_Rate,Department,Distance_From_Home,Education,Education_Field,Employee_Count,Employee_Number,Environment_Satisfaction,Gender,Hourly_Rate,Job_Involvement,Job_Level,Job_Role,Job_Satisfaction,Marital_Status,Monthly_Income,Monthly_Rate,NumCompanies_Worked,Over18,Over_Time,Percent_Salary_Hike,Performance_Rating,Relationship_Satisfaction,Standard_Hours,Stock_Option_Level,Total_Working_Years,Training_Times_LastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,age_group,Experience_Group,Attrition_flag,Month
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5,36-45,5+,1,Jan-1900
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7,45+,5+,0,Jan-1900
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0,36-45,0-2,1,Jan-1900
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0,25-35,5+,0,Jan-1900
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2,25-35,3-5,0,Jan-1900

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 39 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1470 non-null   int64
 1   Attrition                  1470 non-null   object
 2   Business_Travel            1470 non-null   object
 3   Daily_Rate                 1470 non-null   int64
 4   Department                 1470 non-null   object
 5   Distance_From_Home         1470 non-null   int64
 6   Education                  1470 non-null   int64
 7   Education_Field            1470 non-null   object
 8   Employee_Count             1470 non-null   int64
 9   Employee_Number            1470 non-null   int64
 10  Environment_Satisfaction   1470 non-null   int64
 11  Gender                     1470 non-null   object
 12  Hourly_Rate                1470 non-null   int64
 13  Job_Involvement            1470 non-null   int64
 14  Job_Level                  1470 non-null   int64
 15  Job_Role                   1470 non-null   object
 16  Job_Satisfaction           1470 non-null   int64
 17  Marital_Status             1470 non-null   object
 18  Monthly_Income             1470 non-null   int64
 19  Monthly_Rate               1470 non-null   int64
 20  NumCompanies_Worked        1470 non-null   int64
 21  Over18                     1470 non-null   object
 22  Over_Time                  1470 non-null   object
 23  Percent_Salary_Hike        1470 non-null   int64
 24  Performance_Rating         1470 non-null   int64
 25  Relationship_Satisfaction  1470 non-null   int64
 26  Standard_Hours             1470 non-null   int64
 27  Stock_Option_Level         1470 non-null   int64
 28  Total_Working_Years        1470 non-null   int64
 29  Training_Times_LastYear    1470 non-null   int64
 30  WorkLifeBalance            1470 non-null   int64
 31  YearsAtCompany             1470 non-null   int64
 32  YearsInCurrentRole         1470 non-null   int64
 33  YearsSinceLastPromotion    1470 non-null   int64
 34  YearsWithCurrManager       1470 non-null   int64
 35  age_group                  1470 non-null   object
 36  Experience_Group           1470 non-null   object
 37  Attrition_flag             1470 non-null   int64
 38  Month                      1470 non-null   object
dtypes: int64(27), object(12)
memory usage: 448.0+ KB

In [14]:
df['Department'].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [24]:
pd.set_option('display.max_columns', None)
df.head()

,Age,Business_Travel,Daily_Rate,Department,Distance_From_Home,Education,Education_Field,Employee_Number,Environment_Satisfaction,Gender,Hourly_Rate,Job_Involvement,Job_Level,Job_Role,Job_Satisfaction,Marital_Status,Monthly_Income,Monthly_Rate,NumCompanies_Worked,Over_Time,Percent_Salary_Hike,Performance_Rating,Relationship_Satisfaction,Stock_Option_Level,Total_Working_Years,Training_Times_LastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,age_group,Experience_Group,Attrition_flag,Month
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5,36-45,5+,1,Jan-1900
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7,45+,5+,0,Jan-1900
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0,36-45,0-2,1,Jan-1900
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0,25-35,5+,0,Jan-1900
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2,25-35,3-5,0,Jan-1900

In [27]:
df.shape
df = df.drop(columns=['Employee_Count','Standard_Hours','Over18','Attrition'])
df.shape

(1470, 35)

In [28]:
df.columns

Index(['Age', 'Business_Travel', 'Daily_Rate', 'Department',
       'Distance_From_Home', 'Education', 'Education_Field', 'Employee_Number',
       'Environment_Satisfaction', 'Gender', 'Hourly_Rate', 'Job_Involvement',
       'Job_Level', 'Job_Role', 'Job_Satisfaction', 'Marital_Status',
       'Monthly_Income', 'Monthly_Rate', 'NumCompanies_Worked', 'Over_Time',
       'Percent_Salary_Hike', 'Performance_Rating',
       'Relationship_Satisfaction', 'Stock_Option_Level',
       'Total_Working_Years', 'Training_Times_LastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'age_group', 'Experience_Group',
       'Attrition_flag', 'Month'],
      dtype='object')

In [31]:
df['Over_Time'].unique()

array(['Yes', 'No'], dtype=object)

In [32]:
df['Over_Time'] = df['Over_Time'].map({'Yes':1,'No':0})

In [33]:
df['Over_Time'].unique()

array([1, 0])

In [34]:
df['Experience_Group'].unique()

array(['5+', '0-2', '3-5'], dtype=object)

In [36]:
df['Percent_Salary_Hike'].describe()

count    1470.000000
mean       15.209524
std         3.659938
min        11.000000
25%        12.000000
50%        14.000000
75%        18.000000
max        25.000000
Name: Percent_Salary_Hike, dtype: float64

In [39]:
df['Monthly_Income'].describe()

count     1470.000000
mean      6502.931293
std       4707.956783
min       1009.000000
25%       2911.000000
50%       4919.000000
75%       8379.000000
max      19999.000000
Name: Monthly_Income, dtype: float64

In [40]:
df['Percent_Salary_Hike'] = pd.qcut(df['Percent_Salary_Hike'], q=3, labels=['Low', 'Medium', 'High'])

In [41]:
df['Monthly_Income_Group'] = pd.qcut(df['Monthly_Income'], q=3, labels=['Low', 'Medium', 'High'])

In [42]:
df['Monthly_Income_Group'].unique()

['Medium', 'Low', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [43]:
df.columns

Index(['Age', 'Business_Travel', 'Daily_Rate', 'Department',
       'Distance_From_Home', 'Education', 'Education_Field', 'Employee_Number',
       'Environment_Satisfaction', 'Gender', 'Hourly_Rate', 'Job_Involvement',
       'Job_Level', 'Job_Role', 'Job_Satisfaction', 'Marital_Status',
       'Monthly_Income', 'Monthly_Rate', 'NumCompanies_Worked', 'Over_Time',
       'Percent_Salary_Hike', 'Performance_Rating',
       'Relationship_Satisfaction', 'Stock_Option_Level',
       'Total_Working_Years', 'Training_Times_LastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'age_group', 'Experience_Group',
       'Attrition_flag', 'Month', 'Monthly_Income_Group'],
      dtype='object')

In [44]:
df.isnull().sum()

Age                          0
Business_Travel              0
Daily_Rate                   0
Department                   0
Distance_From_Home           0
Education                    0
Education_Field              0
Employee_Number              0
Environment_Satisfaction     0
Gender                       0
Hourly_Rate                  0
Job_Involvement              0
Job_Level                    0
Job_Role                     0
Job_Satisfaction             0
Marital_Status               0
Monthly_Income               0
Monthly_Rate                 0
NumCompanies_Worked          0
Over_Time                    0
Percent_Salary_Hike          0
Performance_Rating           0
Relationship_Satisfaction    0
Stock_Option_Level           0
Total_Working_Years          0
Training_Times_LastYear      0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager         0
age_group                    0
Experience_Group             0
Attrition_flag               0
Month                        0
Monthly_Income_Group         0
dtype: int64

In [45]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 1.6 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [46]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:root%40123@localhost:3306/learning_projects")

In [47]:
df.to_sql(
    name='hr_dataset',
    con=engine,
    index=False,
    if_exists='replace'
)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [48]:
df.to_csv('hr dataset.csv', index=False)

In [50]:
from google.colab import files
files.download('hr dataset.csv')